version: '3'

services:
  fastapi:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:80"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - API_ADDRESS=http://fastapi:80
    depends_on:
      - fastapi
