name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # デプロイするブランチを指定
  workflow_dispatch:

permissions:
    id-token: write
    contents: read
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v2

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd

    - name: 'variable test'
      run: |
          echo ${{ env.RESOURCE_GROUP }}

    - name: 'Create App Service Plan'
      run: |
        az appservice plan create --name ${{ env.SERVICE_PLAN }} --resource-group ${{ env.RESOURCE_GROUP }} --location japaneast --sku B1 --is-linux

    - name: 'Create Web App'
      run: |
        az webapp create --resource-group ${{ env.RESOURCE_GROUP }} --plan ${{ env.SERVICE_PLAN }} --name ${{ env.APP_NAME }} --runtime "PYTHON|3.12"

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_NAME }}
        slot-name: 'production'
        package: '.'
        #publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
